### ISSUE TITLE
nil.union(something_not_nil)

### ISSUE THREAD

**Issue by Alagaesia93** [brianhempel/active_record_union#17]
I suppose it's not a bug, but maybe someone has found a workaround.

I have 6 objects initialised with 6 total different queries and I want to chain unions. 

obj1.union(obj2).union(obj3) and so on

Each one can be nil, and I want to union all the results. There is no default (otherwise I could use default_obj.union(obj1) and so on).

Any ideas?

**Comment by brianhempel** [comment]
```ruby
[query1, query2, query3, query4, query5, query6].compact.reduce(:union)
```
