### ISSUE TITLE
Test suite depends on activerecord version

### ISSUE THREAD

**Issue by pic** [brianhempel/active_record_union#2]
it is green with activerecord 4.0.13,
1 failure with activerecord 4.0.8,
6 failures with activerecord 4.2.0 (but union apparently works without problems).

Different versions of activerecord build different SQL statement, but the test suite is comparing #to_sql to an expected SQL string.

I have no idea how this could be easily fixed.

**Comment by brianhempel** [comment]
All such problems have solutions. Bug me in a week if I haven't gotten around to fixing it yet.

**Comment by brianhempel** [comment]
I updated the tests to match Rails 4.2 output. I am not so concerned about older AR versions since the function of the gem is unchanged.
