### ISSUE TITLE
Associated scopes – Major security issue

### ISSUE THREAD

**Issue by ianaverno** [brianhempel/active_record_union#20]
When `union` is used in scopes
And the scope is called on a parent model instance
Then the scope set by association is ignored

Expected behavior:
Using `union` does not reset association scope

abstract example:
There are multiple communities, each have events, each of which in turn `has_many :groups` or a `all_groups: true` flag, hence need some scopes for easy access
let's say we have two scopes 
```
scope :for_all_groups, -> { where(all_groups: true) }

scope :exclusively_for_groups, -> (group_ids) {joins(:groups).where(all_groups: false).where("groups.id IN (?)", group_ids)}

scope :for_groups, -> (group_ids) { exclusively_for_groups(group_ids).union(for_all_groups) }
```
not the latter properly unites the first scopes, but, even when called on a community, will return events with all_groups: true, for ALL communities.

Either I'm misusing the gem, or it's a huge security issue

**Comment by brianhempel** [comment]
Read the email notification of your original post: did you discover the problem? Is this a non-issue?

**Comment by ianaverno** [comment]
Yes, sorry, this was a concern for us, but it turned out, that this was submitted by mistake, sorry

**Comment by brianhempel** [comment]
So no bug in the gem?
